version: '3'
services:
  #db:
    #image: postgres
    #volumes:
      #- ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:setup && bundle exec rails db:migrate && rm -f /authentication_ms/tmp/pids/server.pid && bundle exec rails s -p 5004 -b 0.0.0.0"
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "5004:5004"
    #depends_on:
      #- db
